# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/webdavnext',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/webdavnext',
                'lib_path': 'webdavnext'},
  'syms': {'webdavnext.core': {'webdavnext.core.foo': ('core.html#foo', 'webdavnext/core.py')}}}
